name: Workflow testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  issues:
    types: [opened, edited]

jobs:
  experimental-great:
    runs-on: ubuntu-latest
    env:
      MY_ENV: "John Doe"

    steps:
      - name: Greet the User
        run: echo "Hello World!"

      - name: List all files in the current directory
        run: ls -l

      - name: Check out our code
        uses: actions/checkout@v3

      - name: Show directory after checkout
        run: ls -l

      - name: Show env vars
        run: |
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR"

